import 'package:biwa_musume_app/models/biwamusume.dart';

class BiwamusumeData {
  static List<Biwamusume> biwamusumeList = [
    const Biwamusume(
      name: 'ニゴイ',
      isHerb: false,
      isCalm: false,
      isNocturnalHabit: false,
      isCarnivorous: false,
      height: 17,
    ),
    Biwamusume(
      name: 'ドジョウ',
      isHerb: false,
      isCalm: false,
      isNocturnalHabit: false,
      isCarnivorous: true,
      height: 11,
    ),
    Biwamusume(
      name: 'イワトコナマズ',
      isHerb: false,
      isCalm: false,
      isNocturnalHabit: false,
      isCarnivorous: true,
      height: 1,
    ),
    Biwamusume(
      name: 'ハクレン',
      isHerb: false,
      isCalm: false,
      isNocturnalHabit: false,
      isCarnivorous: true,
      height: 100,
    ),
    Biwamusume(
      name: 'ビワコオオナマズ',
      isHerb: false,
      isCalm: false,
      isNocturnalHabit: true,
      isCarnivorous: true,
      height: 120,
    ),
    Biwamusume(
      name: 'オオクチバス',
      isHerb: false,
      isCalm: false,
      isNocturnalHabit: true,
      isCarnivorous: true,
      height: 40,
    ),
    Biwamusume(
      name: 'ハス',
      isHerb: false,
      isCalm: false,
      isNocturnalHabit: true,
      isCarnivorous: true,
      height: 30,
    ),
    Biwamusume(
      name: 'ユアユ',
      isHerb: false,
      isCalm: false,
      isNocturnalHabit: true,
      isCarnivorous: true,
      height: 40,
    ),
    Biwamusume(
      name: 'イサザ',
      isHerb: false,
      isCalm: true,
      isNocturnalHabit: false,
      isCarnivorous: false,
      height: 30,
    ),
    Biwamusume(
      name: 'ニゴロブナ',
      isHerb: false,
      isCalm: true,
      isNocturnalHabit: false,
      isCarnivorous: false,
      height: 12,
    ),
    Biwamusume(
      name: 'ウツセミカジカ',
      isHerb: false,
      isCalm: true,
      isNocturnalHabit: false,
      isCarnivorous: true,
      height: 12,
    ),
    Biwamusume(
      name: 'タテボシガイ',
      isHerb: false,
      isCalm: true,
      isNocturnalHabit: false,
      isCarnivorous: false,
      height: 5,
    ),
    Biwamusume(
      name: 'セタシジミ',
      isHerb: false,
      isCalm: true,
      isNocturnalHabit: true,
      isCarnivorous: false,
      height: 3,
    ),
    Biwamusume(
      name: 'スジエビ',
      isHerb: false,
      isCalm: true,
      isNocturnalHabit: true,
      isCarnivorous: false,
      height: 4,
    ),
    Biwamusume(
      name: 'ウナギ',
      isHerb: false,
      isCalm: true,
      isNocturnalHabit: true,
      isCarnivorous: true,
      height: 45,
    ),
    Biwamusume(
      name: 'スッポン',
      isHerb: false,
      isCalm: true,
      isNocturnalHabit: true,
      isCarnivorous: true,
      height: 39,
    ),
    Biwamusume(
      name: 'コイ',
      isHerb: true,
      isCalm: false,
      isNocturnalHabit: false,
      isCarnivorous: false,
      height: 60,
    ),
    Biwamusume(
      name: 'トウヨシノボリ',
      isHerb: true,
      isCalm: false,
      isNocturnalHabit: false,
      isCarnivorous: false,
      height: 7,
    ),
    Biwamusume(
        name: 'スゴモロコ',
        isHerb: true,
        isCalm: false,
        isNocturnalHabit: false,
        isCarnivorous: true,
        height: 12),
    Biwamusume(
        name: 'ムギツク',
        isHerb: true,
        isCalm: false,
        isNocturnalHabit: false,
        isCarnivorous: true,
        height: 10),
    Biwamusume(
        name: 'ビワマス',
        isHerb: true,
        isCalm: false,
        isNocturnalHabit: true,
        isCarnivorous: false,
        height: 30),
    Biwamusume(
        name: 'ライギョ',
        isHerb: true,
        isCalm: false,
        isNocturnalHabit: true,
        isCarnivorous: false,
        height: 55),
    Biwamusume(
        name: 'ホンモロコ',
        isHerb: true,
        isCalm: false,
        isNocturnalHabit: true,
        isCarnivorous: true,
        height: 14),
    Biwamusume(
        name: 'ブルーギル',
        isHerb: true,
        isCalm: false,
        isNocturnalHabit: true,
        isCarnivorous: true,
        height: 15),
    Biwamusume(
        name: 'メダカ',
        isHerb: true,
        isCalm: true,
        isNocturnalHabit: false,
        isCarnivorous: false,
        height: 4),
    Biwamusume(
        name: 'ゴリ',
        isHerb: true,
        isCalm: true,
        isNocturnalHabit: false,
        isCarnivorous: false,
        height: 2),
    Biwamusume(
        name: 'フナ',
        isHerb: true,
        isCalm: true,
        isNocturnalHabit: false,
        isCarnivorous: false,
        height: 20),
    Biwamusume(
        name: 'アブラヒガイ',
        isHerb: true,
        isCalm: true,
        isNocturnalHabit: false,
        isCarnivorous: false,
        height: 20),
    Biwamusume(
        name: 'ビワヒガイ',
        isHerb: true,
        isCalm: true,
        isNocturnalHabit: true,
        isCarnivorous: false,
        height: 10),
    Biwamusume(
        name: 'ワタカ',
        isHerb: true,
        isCalm: true,
        isNocturnalHabit: true,
        isCarnivorous: false,
        height: 30),
    Biwamusume(
        name: 'ヌマチチブ',
        isHerb: true,
        isCalm: true,
        isNocturnalHabit: true,
        isCarnivorous: true,
        height: 12),
    Biwamusume(
        name: 'ワカサギ',
        isHerb: true,
        isCalm: true,
        isNocturnalHabit: true,
        isCarnivorous: true,
        height: 15),
  ];
}
